### ISSUE TITLE
Error occurred while enabling CompassEx v1.1.0 (Is it up to date?)

### ISSUE THREAD

**Issue by liquidox** [Philipp15b/CompassEx#12] opened 2012-11-04 15:32 UTC
With latest Bukkit Beta, fresh jar and config:

2012-11-04 16:31:22 [SEVERE] Error occurred while enabling CompassEx v1.1.0 (Is it up to date?)
java.lang.NullPointerException
        at de.philworld.bukkit.compassex.CompassEx.onEnable(CompassEx.java:123)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:298)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:280)
        at net.minecraft.server.MinecraftServer.j(MinecraftServer.java:320)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:299)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:258)
        at net.minecraft.server.DedicatedServer.init(DedicatedServer.java:141)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:400)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:818)

**Comment by Philipp15b** [comment] 2012-11-04 15:58
This is weird. This only happens if the command is not registered, when either the `plugin.yml` is wrong or missing. But the file hasn't changed for 8 months / since 0.9.0. This must be a bug in Bukkit.

**Comment by liquidox** [comment] 2012-11-04 16:31
Could be related to Commandbook having /compass then.

However, when I try to use the aliases, it shows the Help page on ANY command, so those are somehow bugging also...

**Comment by Philipp15b** [comment] 2012-11-04 17:03
Does the error occur only on the Bukkit _Beta_  or on other versions of Bukkit?

**Comment by liquidox** [comment] 2012-11-04 17:10
Only tried Beta, sorry :/

**Comment by liquidox** [comment] 2012-11-10 08:32
Any luck here?

**Comment by Philipp15b** [comment] 2012-11-10 14:52
So just to be sure, we're talking about 1.4.2-R0.2 ([Build #02455](http://dl.bukkit.org/downloads/craftbukkit/view/01542_1.4.2-R0.2/))? I tried it, but I could not reproduce the error.

**Comment by liquidox** [comment] 2012-11-14 09:05
Still unable to load plugin even on 1.4.4 builds.

**Comment by Philipp15b** [comment] 2012-11-17 11:26
I just tested it again with [Bukkit build #2468](http://dl.bukkit.org/downloads/craftbukkit/view/01571_1.4.4-R0.1/) (1.4.4-R0.1). I still do not get an error (even when using CommandBook 2.1). I will close the issue now as I cannot reproduce it. Maybe you could try it with just Bukkit and CompassEx to be sure that this is not caused by other plugins somehow.

**Closed as completed by Philipp15b** 2012-11-17 11:26 UTC
